[package]
name = "hb-node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "1.0.6" }
runtime_io = { package = "sp-io", path = "../../../primitives/io" }
state_machine = { package = "sp-state-machine", path = "../../../primitives/state-machine" }
substrate-executor = { package = "sc-executor",path = "../../../client/executor" }
primitives = { package = "sp-core", path = "../../../primitives/core" }
trie = { package = "sp-trie", path = "../../../primitives/trie" }
hb-node-primitives = { path = "../primitives" }
hb-node-runtime = { path = "../runtime" }

[dev-dependencies]
test-client = { package = "substrate-test-client", path = "../../../test-utils/client" }
sp-runtime = { path = "../../../primitives/runtime" }
runtime_support = { package = "frame-support", path = "../../../frame/support" }
balances = { package = "pallet-balances", path = "../../../frame/balances" }
session = { package = "pallet-session", path = "../../../frame/session" }
staking = { package = "pallet-staking", path = "../../../frame/staking" }
system = { package = "frame-system", path = "../../../frame/system" }
timestamp = { package = "pallet-timestamp", path = "../../../frame/timestamp" }
treasury = { package = "pallet-treasury", path = "../../../frame/treasury" }
contracts = { package = "pallet-contracts", path = "../../../frame/contracts" }
indices = { package = "pallet-indices", path = "../../../frame/indices" }
wabt = "0.9.2"
criterion = "0.3.0"

[features]
wasmtime = [
    "substrate-executor/wasmtime",
]
stress-test = []
wasmi-errno = [
	"substrate-executor/wasmi-errno",
]